# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 70

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  customCSS = ["css/custom.css"]
  autoFeaturedImage = false
