# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 1

[[main]]
  name = "About & Contact"
  pageRef = "about/about.md"
  weight = 2

[[main]]
  name = "RSS"
  url = "https://coefficiencies.com/posts/index.xml"
  weight = 40
  [main.params]
    icon = "RSS"
    showName = false
    target = "_blank"

# [[main]]
#   name = "GitHub"
#   url = "https://github.com/jpanther/congo"
#   weight = 40
#   [main.params]
#     icon = "github"
#     showName = false
#     target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

# [[main]]
#   identifier = "locale"
#   weight = 100
#   [main.params]
#     action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
